### ISSUE TITLE
Batchsize's effection 

### ISSUE THREAD

**Issue by Sundragon1993** [itsyoboieltr/anpr-ai#1]
Dear author, thank you so much for the contribution!

I was wondering if you have tuned the batch size. Did 4 is your intention?, I've trained the network with batchsize=32 and the results are worse than yours.
Thank you!

**Comment by itsyoboieltr** [comment]
Hello @Sundragon1993! 

The batch size of 4 was definitely my intention, since my system does not have enough memory to be able to take more.

The fact, that your results are worse, could be for several possible reasons, not necessarily for the higher batch size you chose. However, it is very much possible that choosing a higher batch size can have this type of impact on the performance of your model.

I would suggest that you experiment with different batch sizes until you find the optimum, starting from highest that is possible for your system (to speed up the training process) to the lowest possible (whose performance is still good enough for your use case, in case you see an improvement if you reduce this parameter).
